USE ProjetFinal_Maillots
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'PasswordBD2024!'
GO
CREATE CERTIFICATE Final_Certificat WITH SUBJECT = 'ChiffrementAdresseCourrielClient'
GO
CREATE SYMMETRIC KEY ProjetFinal_Cle WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE Final_Certificat
GO
